create_ticket:
  fields:
    device_id:
      required: true
      example: "4e44822107eb214b9065fb0cc7148bac"
      selector:
        text:
    subject:
      required: true
      example: "Water leak detected"
      selector:
        text:
    text:
      required: true
      example: "Sensor triggered at 10:30 AM"
      selector:
        text:
          multiline: true

sync_assets:
  fields:
    device_id:
      required: false
      example: "4e44822107eb214b9065fb0cc7148bac"
      selector:
        text:
